### ISSUE TITLE
compatibility with upcoming R72 of three.js

### ISSUE THREAD

**Issue by vincent-courtalon** [squarefeet/ShaderParticleEngine#75] opened 2015-08-31 03:59 UTC
Hello, i am not sure if it is really a bug or just a temporary change from R72 dev version of three.js, but using the shaderParticleEngine with it does not work for me (it works with r71 of three.js)
it makes a webgl warning "WARNING: Attribute 0 is disabled. This has signficant performance penalty" on chrome, and the particles are not visible...

if you have any idea of a quick fix (some suggestion i found was using index0AttributeName on material)? I will try later to pinpoint at what commit of three.js it happen.

and thank you for this project, it is a really fast particle engine!

**Comment by titansoftime** [comment] 2015-09-01 05:16
In the dev version as of this post I get this error: ``THREE.ShaderMaterial: attributes should now be defined in THREE.BufferGeometry instead.``

**Comment by titansoftime** [comment] 2015-09-15 17:36
@squarefeet r72 is now live. Unfortunately (once again) there are no release notes /sigh.

**Comment by weiserhei** [comment] 2015-09-16 13:41
Changelog is up :page_facing_up:  https://github.com/mrdoob/three.js/releases/tag/r72

I will also migrate my projects shortly and test SPE with r72.

**Comment by squarefeet** [comment] 2015-09-17 18:24
Hey guys, sorry for the delay in getting back to you all. 

Going to grab me some r72 action and see how it fairs; will try to resolve any bugs with it should I (probably) come across any.

Thanks for the heads up :)

**Comment by squarefeet** [comment] 2015-09-17 18:30
Okay, first problem I can see is that Shader Material seems to only play ball with `THREE.BufferGeometry` instances now (rather than plain ol' `THREE.Geometry` instances, and at least when custom attributes are being used), so I'll jump on that!

**Comment by titansoftime** [comment] 2015-09-17 19:36
@squarefeet Awesome! Super happy to see you on this =]

Your hard work is much appreciated. This library kicks ass.

**Comment by squarefeet** [comment] 2015-09-17 19:39
@titansoftime Ha, no worries, Walter ;) It may take me a few days to get it up and running (got to convert from Geometry -> BufferGeometry, and don't want to cut any corners), but I'll be playing in the `dev` branch if you feel like coming along for the ride or want to point out I'm going in a stupid direction.

Currently wondering whether I should store all attribute values in a single ArrayBuffer (per emitter), using Float32Arrays as windows into the buffer, or whether a single buffer-per-attribute would be fine. Not sure of any performance gains from doing the former, nor the latter. Any ideas?

**Comment by titansoftime** [comment] 2015-09-17 19:44
> Ha, no worries, Walter ;)

HA! I don't roll on SHABBOS!!

> Not sure of any performance gains from doing the former, nor the latter.

I'm right there with you, not sure. Sorry for my complete uselessness there =]

**Comment by squarefeet** [comment] 2015-09-17 19:46
Saturday, Donny, is Shabbos, the Jewish day of rest. That means that I don't work, I don't drive a car, I don't fucking ride in a car, I don't handle money, I don't turn on the oven, and I sure as shit *don't fucking roll*!

**Comment by titansoftime** [comment] 2015-09-17 20:19
"I'm calmer than you are."

**Comment by glibersat** [comment] 2015-10-05 15:54
thx @squarefeet for having started the port to r72, I can't wait for it to be released! :)

**Comment by squarefeet** [comment] 2015-10-05 18:23
@glibersat No worries, sorry it's taking so long - life is getting in the way!

**Comment by andrislusis** [comment] 2015-10-06 23:19
indeed thx @squarefeet for the effort, I am on the waiting list for the port as well. :)

**Comment by squarefeet** [comment] 2015-10-07 16:34
Okay, should have some free time coming up this week and over the weekend, so will hopefully have something up next week. Will keep this thread updated with progress! Hang tight, and thanks for the patience!

**Comment by titansoftime** [comment] 2015-10-07 16:47
Ha, yea I started working on this (more so just playing around to better understand the code) and holy crap. Not an easy task. Your efforts are most certainly appreciated =]

**Comment by squarefeet** [comment] 2015-10-07 16:50
Ha, thanks. I reckon if I switch over most of the `utils` functions to work on TypedArrays, that'll make life quite a lot easier, and everything else should fall into place... 

Famous last words ;)

What I don't want to do is create a bunch of Vec3s only to use them as storage to place into larger TypedArrays, performance would be terrible; whereas if I work directly on the TypedArray buffer then we might even see a little bit of a speed-up...Maybe! Definitely get a tiny boost from using BufferGeometry instead, that's for sure.

**Comment by titansoftime** [comment] 2015-10-07 16:51
> What I don't want to do is create a bunch of Vec3s only to use them as storage to place into larger TypedArrays

Ha yea that's exactly what I was doing as a test. Scrapped it as a foreseen waste of a time.

**Comment by squarefeet** [comment] 2015-10-07 16:51
And exactly what I started doing, too!

**Comment by titansoftime** [comment] 2015-10-07 16:55
> Definitely get a tiny boost from using BufferGeometry instead, that's for sure.

Definitely more efficient memory usage. Should help out on the delay of pushing the data to gpu on initial render. Scenes with dynamically loaded particles (mine for example) should benefit big time.

**Comment by squarefeet** [comment] 2015-10-07 16:56
Yepyep, finger's crossed. The more I think about this port to r72, the more I want to scrap a lot of the library as it is and start not-quite-from-scratch, rather than bastardise what's here already into working how it wasn't designed to! Experiments ahoy...

**Comment by squarefeet** [comment] 2015-10-07 21:47
Throwing this out there for opinions:

Would people using this lib be bothered if I slightly changed the way emitter properties were set? 

Current way:

```
var emitter = new SPE.Emitter( {
    sizeStart: 1,
    sizeMiddle: 10,
    sizeEnd: 5,
    // etc.
} );
```

Potential new way:

```
var emitter = new SPE.Emitter( {
    size: {
        start: 1,
        middle: 10,
        end: 5
    },
    // etc., same structure for other props such as `opacity` and `angle`
} );

// Or:
var emitter = new SPE.Emitter( {
    size: new SPE.ValueOverLifetime( 1, 10, 5, ... ), // Allows for more than three values
    // etc., same structure for other props such as `opacity` and `angle`
} );
```

Nothing's set-in-stone yet (as I've not started attacking this bit), so willing to go with general consensus here, and maybe support both options to allow backward compatibility.

Do let me know!

**Comment by titansoftime** [comment] 2015-10-07 22:27
I like both new methods over the current. A little bit of rewrite is totally worth it IMO.

The first new option looks really clean. The second option looks less clean but more flexible.

I'd have to side with improved functionality over cleaner code.

That's my 2 cents.

**Comment by squarefeet** [comment] 2015-10-07 22:30
The second option could easily just be an array, actually. Less obvious what it's values are representing, though, I guess.

I'm just rather conscious of causing people to rewrite their code! I'm thinking of nicking ideas from an [old v2 of this lib](https://vimeo.com/106543067) (video) I made a while back but never finished...

**Comment by titansoftime** [comment] 2015-10-07 22:33
> I'm just rather conscious of causing people to rewrite their code!

I hear ya.

That video is very impressive. Very cool! I love the collision one as well. Mind blowing work man.

**Comment by squarefeet** [comment] 2015-10-07 22:34
Thanks :) The collision was such a PITA. Don't want to revisit that again for a while! I'll see if I can whack CurlNoise support in after I've supported r72.

**Comment by titansoftime** [comment] 2015-10-07 22:35
> The collision was such a PITA

I can only imagine hehe.

**Comment by squarefeet** [comment] 2015-10-07 23:46
Started making decent headway on this. Party's on the `dev` branch (where all the good parties are) in a temp folder called `typedSrc`, and is a complete rewrite. Long way to go, but seems to be a good start :)

**Comment by vincent-courtalon** [comment] 2015-10-08 16:34
Personally, i am ok with both new version, perferably the one with more fonctionnality.
And thanks again for you're work on this library, it is greatly appreciated. I tried to poke in the code, but it still is a little to much for me for now (for my understanding of three.js internals and webgl shaders), Very interesting.

**Comment by squarefeet** [comment] 2015-10-09 01:23
Cheers for the feedback @vincent-courtalon. 

I've hit a massive brick wall, and looks like I'll only be able to support a max of 4 values for valueOverLifetime properties (like color, opacity, size, angle). Stupid GLSL doesn't like non-constants in loops. Might be able to work around it but would need to build shaders dynamically and don't want to go down that route just yet!

Some good news, though: I've got the re-write drawing particles on-screen, and interpolating between various values... Got it up past 2 million particles before I saw a drop below 60fps, so there is a rather nice performance gain so far!

Will try to have a beta out by the end of the weekend, if not shortly after.

**Comment by titansoftime** [comment] 2015-10-09 01:32
> Stupid GLSL doesn't like non-constants in loops.

That is stupid.

> Will try to have a beta out by the end of the weekend, if not shortly after.

Hazaa!

**Comment by squarefeet** [comment] 2015-10-09 09:15
Stupid, but it makes sense when you consider how it's compiled. Finger's crossed!

**Comment by squarefeet** [comment] 2015-10-10 02:04
Quick update on the rewrite:

Done 
-------

* Particles are being drawn (!)
* Forces (`velocity`, `acceleration`, and a new one: `drag`) are integrated as per current version. Should mean behaviour is consistent when switching to this new version.
* Added new `drag` parameter. Reduces velocity of a particle over it's lifetime according to float value between `0.0` and `1.0` (clamped if < 0 or > 1).
* All parameters for `SPE.Emitter` are now defined as following (values are just examples, not every parameter is a `THREE.Vector3` instance):
```javascript
// For properties that don't change over time:
// position, velocity, acceleration, drag
parameterName: {
    value: new THREE.Vector3(),
    spread: new THREE.Vector3()
}

// For props that DO change over time:
// color, opacity, angle, size
parameterName: {
    value: [0, 1, 0], // Array can be any length. Is later interpolated to length of 3.
    spread: [10, 10, 10] // Array can be any length. Is later interpolated to length of 3.
}
```

* All GLSL branching has been factored out (win).
* Colours are now packed into one attribute, freeing up to attribute spaces for future adventures.


Todo
-------
* Add emitting behaviour (currently all particles rendered at once!)
* Add particle reset to emitter.
* Add ability to change values at runtime (considering using `THREE.BufferAttribute`'s `updateRange` for performance).
* Add optional `scale` param to `SPE.Group` to fix #66.
* Add emitter pooling to `SPE.Group`.
* Add proper emitter removal from group.
* Consider adding unit tests.
* Consider supporting arrays of length 4 for params that change over time, not current limit of 3
* Optimise the crap out of everything (GLSL is looking ok at the moment).
* Probably some other stuff I've forgotten.


Looks like a lot left to do, but the core is there and seems pretty solid :+1:

**Comment by titansoftime** [comment] 2015-10-10 02:47
I cannot wait to try this out!

**Comment by squarefeet** [comment] 2015-10-12 01:24
**Update Time!**

**Done**
* Emitting behaviour is in place and stable. Bit neater than previously.
* `maxAge` is now a per-particle `SPE.Emitter` property, and supports spread values (meaning each particle can have its own maximum age).
* Added rotation support, with `axis` (Vector3), `angle`, `angleSpread`, `speed` and `speedSpread`. Emitters can now be rotated around an arbitrary axis, either statically or to reach rotation angle over particle's lifetime. All rotation properties apart from `axis` are per-particle.
* Value-over-lifetime properties can now be manually adjusted to have between 1 and 4 values. This solves an interpolation problem. Eg. an opacity value of `[0, 1, 0]` to length 4 is interpolated as `[0, 0.66, 0.66, 0]`, which isn't ideal, so in this case you'd set `SPE.valueOverLifetime` to 3. 
    * It's a global property, so will affect ALL emitters, and ALL groups.
* Re-randomising particles can be controlled via a custom `randomise` key/value pair on each `SPE.Emitter` property. It's currently disabled, though, until I figure out a way to update buffer attributes without re-sending the entire attribute buffer to the GPU.


**Todo**
* `SPE.Group`'s `scale` property.
* Pooling
* Emitter removal from group.
* Runtime value changing.
* DISC emitter support (Might drop this in favour of using SPHERE with a zeroed-out z-value).
* Proper documentation!

So yeah, making good progress, plus emitter rotation is pretty neat. It's still nice and speedy, too.

**Comment by titansoftime** [comment] 2015-10-12 02:42
Hell yea man, awesome!

**Comment by glibersat** [comment] 2015-10-12 08:04
Waho, thank you so much for the work! Can't wait for the beta build :) Cheers!

**Comment by squarefeet** [comment] 2015-10-12 23:10
Update time!
-----------------

**Done**
* Added [documentation](https://github.com/squarefeet/ShaderParticleEngine/tree/dev/typedSrc/docs) (yay). Incomplete, but is a good start.
* Fixed up issues with `SPE.Emitter.rotation` values in the shader. 
* Correctly calculate particle `drag` amount in the shader.
* Allowed for an emitter's `rotation` to be static, or applied over a particle's lifetime.
* Optimised the shaders a little.
* Buffer updating is only done on the particular sections of a buffer that have changed. Buffers that have changed no longer send their entire value to the GPU each frame. Win.
* Added a `wiggle` property to `SPE.Emitter`. It wiggles, or jiggles, or waggles particles about. Useful for fire embers.

**Todo**
* Filling in the rest of the existing Group and Emitter APIs. Should be a fairly quick process.
* DISC distribution support.
* Consider adding TRIANGLE distribution support.
* Group's `scale` property.
* Runtime value changing.

I'll have a beta build tomorrow, with shaders in the right place (not in a random HTML file!), and stuff organised a little better. It won't be feature-complete (definitely won't have runtime value changing), but will hopefully have the rest of the Group and Emitter APIs in place :)

Phew... almost there. Must sleep..!

**Comment by titansoftime** [comment] 2015-10-13 03:22
Super excited for this!

**Comment by squarefeet** [comment] 2015-10-13 19:14
Once I've got this new version feature-complete, I'm thinking about adding support for texture sprites that would animate over time... Sound good?

**Comment by titansoftime** [comment] 2015-10-13 20:09
Sounds cool =]

**Comment by squarefeet** [comment] 2015-10-13 22:32
**Update time, and first r72-supporting beta release!**

**Done**
* Added remaining SPE.Emitter functions. SPE.Emitter is now feature complete (currently a bug with re-randomising particles, but I know the cause so will be fixed ASAP, and no DISC distribution support yet).
* Added remaining SPE.Group functions. SPE.Group is now feature complete.
* Added `activeMultiplier` to SPE.Emitter options that replaces the old behaviour of emitter's `alive` property.
* Moved shaders to live in `SPE.shaders` object, and broke them up into more manageable chunks.
* Updated project's Gruntfile.
* Built first beta release, available [here](https://github.com/squarefeet/ShaderParticleEngine/tree/dev/build/).
* Re-organised folder structure. Removed `typedSrc`, promoted that to `src`, moved `docs` folder to root, moved placeholder `presets` folder to root.

**Todo**
* Runtime value changing.
* Group's `scale` property.
* DISC distribution support.
* Testing of emitter pooling.
* Add fog support.


The documentation isn't quite yet complete, but I'll get that done as soon as I can. 

In the meantime, feel free to grab the new build [here](https://github.com/squarefeet/ShaderParticleEngine/tree/dev/build/), and give it a whirl. [This file](https://github.com/squarefeet/ShaderParticleEngine/blob/dev/tests/index.html) is where I'm testing it, and I've made sure to include all available options in there so it should be a bit easier to play around with.

None of the examples are updated to this build, so they won't work. Yet.

Please open any new issues if (when!) you see them and mark them as "[BETA]".

Thanks! :)

**Comment by titansoftime** [comment] 2015-10-14 04:19
WOOOOOOOO!!!!!!!!!!!!

Very nicely done! The integration was seamless. It took about 10 minutes. Much cleaner API. So far (I've done only minor testing) everything looks good =]

**Comment by squarefeet** [comment] 2015-10-14 22:34
Awesome, glad to hear it. 

Will continue working on the runtime value changing, DISC distribution, then start on optimisation, then thorough testing. Once that's done, I daresay it'll be ready for release.

**Comment by squarefeet** [comment] 2015-10-16 00:03
**Super fun happy update time!**

**Done**
* Runtime parameter updates for `position`, `velocity`, `acceleration`, `drag`.
    * Other buffer attributes are currently being updated when parameters are changed (the difficult bit!), but no functions in `SPE.Emitter` to recalculate values yet (the easy bit).

**Todo**
* Test Emitter pooling.
* Add DISC distribution support.
* General optimisation.

**Extra**
* Started playing around with spritesheet support. Getting there, but need to properly figure out and apply the maths.


SO DAMN CLOSE!

**Comment by squarefeet** [comment] 2015-10-16 12:37
DISC distribution type is now supported.

**Comment by titansoftime** [comment] 2015-10-16 22:50
Nice!

One thing though: the new ``SPE.valueOverLifetimeLength: 3`` causes particles not to be visible (for me at least). Changeing the value back to 4 solves it.

**Comment by squarefeet** [comment] 2015-10-16 22:51
How odd. I did find a silly problem with my value-over-lifetime calculations in the shaders earlier, but fixed that (not on `dev` branch yet). Could you post up your emitter settings where you're seeing this issue, in a gist or something?

**Comment by titansoftime** [comment] 2015-10-16 23:11
I don't have much time at the moment, but I can do this:

```
			particleTexture = this.params.map ? ENGINE.loadCachedTexture('/img/particles/' + this.params.map + '.png') : null;
			particleArray   = ENGINE.mc.get('particleArray');
			
			this.particleGroup = new SPE.Group({
				
				texture: particleTexture,
				fog: true
				
			});
			
			if( !this.initpos ){
			
				if( this.params.initPos ){
					
					this.initpos = this.params.initPos;
					
				}else{
					
					this.initpos = new THREE.Vector3();
					
				}
			
			}
			
			var type;
			switch( this.params.type ){
				
				case 'cube':
					type = SPE.distributions.BOX;
					break;
					
				case 'sphere':
					type = SPE.distributions.SPHERE;
					break;
				
			}
			
			this.emitter = new SPE.Emitter( {
				
				particleCount: parseInt(this.params.resolution),
				
				maxAge: {
					value: parseInt(this.params.maxAge),
					spread: 0
				},
				
				position: {
					value: this.initpos,
					spread: this.params.positionSpread,
					spreadClamp: new THREE.Vector3( 0, 0, 0 ),
					distribution: type,
					randomise: false
				},
				
				radius: {
					value: parseFloat(this.params.radius),
					spread: 0,
					scale: new THREE.Vector3( 1, 1, 1 )
				},
				
				velocity: {
					value: this.params.velocity,
					spread: this.params.velocitySpread,
					distribution: type,
					randomise: false
				},
				
				acceleration: {
					value: this.params.acceleration,
					spread: this.params.accelerationSpread,
					distribution: type,
					randomise: false
				},
				
				drag: {
					value: 0,
					spread: 0
				},
				
				wiggle: {
					value: parseInt(this.params.wiggle),
					spread: parseInt(this.params.wiggleSpread)
				},
				
				/*
				rotation: {
					axis: new THREE.Vector3( 0, 1, 0 ),
					axisSpread: new THREE.Vector3( 0, 0, 0 ),
					angle:  Math.PI * 0.5, // radians
					angleSpread: 0, // radians
					static: false,
					center: new THREE.Vector3( 0, 0, 0 )
				},
				*/
				
				size: {
					value: this.params.size,
					spread: this.params.sizeSpread,
				},
				
				speed: {
					value: parseFloat(this.params.speed),
					spread: parseFloat(this.params.speedSpread),
				},				
				
				color: {
					value: [this.params.colorStart, this.params.colorMiddle, this.params.colorEnd ]
				},
				
				opacity: {
					value: this.params.opacity,
					spread: this.params.opacitySpread
				},
				
				angle: {
					value: 0,
					spread: 0
				}
				
				// duration: 5,
				// activeMultiplier: 1,
				// isStatic: true

			});
			
			if( parseInt(this.params.duration) ){
				
				this.emitter.duration = parseInt(this.params.duration);
				
			}
```

```
//dagger gold
				params = {
					
					type                : 'cube',		
					velocity            : new THREE.Vector3(0,4,0),			
					velocitySpread      : new THREE.Vector3(0,6,0),					
					positionSpread      : new THREE.Vector3(1,0,1),					
					colorStart          : new THREE.Color(1,0.9,0.1),
					colorMiddle         : new THREE.Color(1,0.9,0.1),
					colorEnd            : new THREE.Color(1,0.9,0.1),
					colorStartSpread    : new THREE.Vector3(10,10,10),			
					duration            : 0,
					maxAge              : 1,
					size                : [1,1,1],
					sizeSpread          : [5,10,5],
					map                 : 4,
					speed               : 1,
					speedSpread         : 3,
					resolution          : 300,
					radius              : 1,
					opacity             : [0,1,0],
					opacitySpread       : [0,0,0],
					angleVelocity       : 1,
					angleStart          : 0,
					acceleration        : new THREE.Vector3(0,0,0),
					accelerationSpread  : new THREE.Vector3(0,0,0),
					initPos             : new THREE.Vector3(0,-1,0)
					
				};
```

**Comment by squarefeet** [comment] 2015-10-16 23:26
I've just pushed a new build to `dev`. Could you give it a whirl and let me know if it helps?

FYI: Not going to be able to do anything else on this until late on Sunday, so keep your existing version just in case!

**Comment by titansoftime** [comment] 2015-10-17 04:18
On this im getting an error: ``Uncaught ReferenceError: emitter is not defined``

here:

```
SPE.Emitter.prototype._assignLifetimeValue = function( index, propName ) {
    var array = this.attributes[ propName ].typedArray,
        prop = emitter[ propName ], // <-------------
        utils = SPE.utils,
        value;

    if ( utils.arrayValuesAreEqual( prop._value ) && utils.arrayValuesAreEqual( prop._spread ) ) {
        value = Math.abs( utils.randomFloat( prop._value[ 0 ], prop._spread[ 0 ] ) );
        array.setVec4Components( index, value, value, value, value );
    }
    else {
        array.setVec4Components( index,
            Math.abs( utils.randomFloat( prop._value[ 0 ], prop._spread[ 0 ] ) ),
            Math.abs( utils.randomFloat( prop._value[ 1 ], prop._spread[ 1 ] ) ),
            Math.abs( utils.randomFloat( prop._value[ 2 ], prop._spread[ 2 ] ) ),
            Math.abs( utils.randomFloat( prop._value[ 3 ], prop._spread[ 3 ] ) )
        );
    }
};
```

**Comment by titansoftime** [comment] 2015-10-17 04:28
Another thing:

After your update with the disc support, I am getting the error: ``Uncaught ReferenceError: paramsUpdateRange is not defined`` when removing a group from the scene.

This previously was not an issue.

This is my removal function:

```

	this.unload = function () {

		var len, i, p, particleArray=[];

		particleArray = ENGINE.mc.get('particleArray');		

		this.clearTimeout();

		if( this.particleGroup ){

			this.particleGroup.removeEmitter(this.emitter);

			if( this.particleGroup.mesh.parent ){

				this.particleGroup.mesh.parent.remove(this.particleGroup.mesh);

			}else{

				ENGINE.scene.remove(this.particleGroup.mesh);

			}

			this.particleGroup.mesh.geometry.dispose();
			this.particleGroup.mesh.material.dispose();			

			this.params = null;
			this.emitter = null;
			this.particleGroup = null;

		}

		len = particleArray.length;
		for (i = len - 1; i >= 0; i--) {

			p = particleArray[i];
			if (p) {

				if (this.name == p.name) {
					
					particleArray.splice(i, 1);
					
				}

			}

		}

		ENGINE.mc.set('particleArray',particleArray);

		if (typeof (this.onunload) == 'function') {

			this.onunload();

		}

	};

```

**Comment by squarefeet** [comment] 2015-10-17 08:16
This is why I should've written unit tests first! Will get around to adding those asap.

In the meantime, I've pushed a new update that should fix your issues. Thanks for testing this for me, it's really appreciated :)

**Comment by yisk** [comment] 2015-10-17 14:00
Why do you use commas instead of semicolons? This is error-prone and confusing as shit.

**Comment by squarefeet** [comment] 2015-10-17 15:29
I like my vars to be declared at the top of functions, lets me know exactly what is defined, rather than having things declared throughout. Never had a problem with accidentally making global vars this way. Not confusing at all.

Potato potato. Tomato tomato.

**Comment by yisk** [comment] 2015-10-17 16:41
Okay, but
```javascript
SPE.method1 = function(){
    ...
} , // why not ";" here?
SPE.method2 = function(){
    ...
}
```

**Comment by squarefeet** [comment] 2015-10-17 19:25
Probably because it's still a beta. And semi colon in that scenario isn't necessary, unless followed by parentheses that would execute the function immediately. And that I rewrote this in ~a week in my spare time.

**Comment by squarefeet** [comment] 2015-10-17 19:25
Comma in that scenario is probs a typo, if that's what you're on about.

**Comment by vincent-courtalon** [comment] 2015-10-17 19:34
this new version look very good, thanks for the work. I have a little bit of time tomorrow so i will try to update my code to use this and i will give you feedback.

**Comment by titansoftime** [comment] 2015-10-17 19:55
> Probably because it's still a beta. And semi colon in that scenario isn't necessary, unless followed by parentheses that would execute the function immediately. And that I rewrote this in ~a week in my spare time.

Yea I noticed those to, Had to fix since I use an auto minify for all my scripts which require syntax perfection unfortunately heh. Not a big deal at all =]

**Comment by squarefeet** [comment] 2015-10-17 20:06
Yeah, I think what yisk is on about is commas after function closing brackets, which are typos, probs from a few copypastas pre-refactor. Stuff like that will be sorted out by the time it's released. Exactly what a beta is for - catch things I missed.

**Comment by titansoftime** [comment] 2015-10-17 23:37
Ok tried current dev build and:

``Uncaught ReferenceError: emitter is not defined``

```
SPE.Emitter.prototype._assignAngleValue = function( index ) {
    var array = this.attributes.angle.typedArray,
        prop = emitter.angle, // <---- here
        utils = SPE.utils,
        value;

    if ( utils.arrayValuesAreEqual( prop._value ) && utils.arrayValuesAreEqual( prop._spread ) ) {
        value = utils.randomFloat( prop._value[ 0 ], prop._spread[ 0 ] );
        array.setVec4Components( index, value, value, value, value );
    }
    else {
        array.setVec4Components( index,
            utils.randomFloat( prop._value[ 0 ], prop._spread[ 0 ] ),
            utils.randomFloat( prop._value[ 1 ], prop._spread[ 1 ] ),
            utils.randomFloat( prop._value[ 2 ], prop._spread[ 2 ] ),
            utils.randomFloat( prop._value[ 3 ], prop._spread[ 3 ] )
        );
    }
};
```

**Comment by squarefeet** [comment] 2015-10-18 00:38
Crap. I need to stop rushing things out. I'll fix it up tomorrow eve. In the meantime, change `emitter` to `this` and all will be fine. 

Apologies for these silly bugs; I'm going to slow things down a little from now on. Rushing fixes out never ends well, whether beta or not - I don't have time to fully test it  Hold fort for the next beta, it'll be a few days; no more hotfixes. 

Also in the meantime: big thanks for being testers, it's hugely appreciated, as is everyone's patience in getting r72 support.

**Comment by squarefeet** [comment] 2015-10-19 01:00
Had more time than I thought I'd have today, so managed to strike quite a few things off the list:

**Done**
* Linted src and added strict mode to functions.
* Removed *only* existing comma typo in the src code that @yisk pointed out.
* Added full JSDoc-based documentation (see new `docs` folder)
* Added annotated source (again, see `docs` folder)
* Added Travis CI (currently only checks `dev` build. Will add `master` branch build status once `dev` is finalised)
* Added Bower support.
* Added Browserify support.
* Added `remove()` function to `SPE.Emitter`
* Ensured that when an emitter is removed from a group, the attribute arrays are spliced accordingly.

**Todo**
* Update/create new examples.
* Create some emitter presets.
* Add some tutorials/guides.
* Finish updating the API changelog / migration doc.
* Final round of testing pre-go live.

**Comment by titansoftime** [comment] 2015-10-19 01:28
Just tested, working great =]

**Comment by squarefeet** [comment] 2015-10-19 20:03
Fantastico. Will get docs up to scratch and finish testing, then hopefully promote to master soon :)

**Comment by yisk** [comment] 2015-10-20 15:46
I really need more examples of complex effects. The library is still far enough from using in production. Let's say I develop a Hearthstone-like CCG for web. How can I reach such effects like a glow around a custom shape? And what about user-defined particle behaviour? Are you consider it to be a bottleneck?

**Comment by squarefeet** [comment] 2015-10-20 15:53
Glow around a shape? Like [this](https://stemkoski.github.io/Three.js/Shader-Glow.html)? 

If you could provide more information about what sort of 'complex effects' you are talking about then I'll be able to help you better.

You could always contribute to the library if you feel something is missing.

**Comment by squarefeet** [comment] 2015-10-20 23:02
**Update**

**Done**
* Testing
* Added `SPE.Group.dispose()`
* Optimised `SPE.Emitter.tick()`. It's ~15-20% faster now.
* Optimised rendering. Will only render sections of buffers in use.
* Fix for when `SPE.Emitter.particleCount` is `1`.

**Todo**
* Examples
* Migration docs
* Presets (low priority)
* Finish overview guide.

**Comment by titansoftime** [comment] 2015-10-21 05:03
Very nice, runs so good =]

**Comment by squarefeet** [comment] 2015-10-22 22:59
**Update**

Ran as many tests as I could think of and everything looked good so I promoted to master.

r72 support is live!

**Closed by squarefeet** 2015-10-22 22:59 UTC

**Comment by titansoftime** [comment] 2015-10-23 06:26
@squarefeet I will assume "Optimised rendering. Will only render sections of buffers in use." meant only rendering particles that are within view frustum. This in my opinion should be an optional thing for the user. There are cases (which I kinda discovered by accident) where a user would want particles from an out of view emitter to be shown, such as projected fire streams on a wide staircase for example.

**Comment by squarefeet** [comment] 2015-10-23 09:23
@titansoftime Not quite. Since three.is hates being given larger typed arrays to a buffer attribute than it was given before the scene was rendered (its fine with shrinking them!) I have to allocated memory/buffer sizes upfront. If you specify a larger buffer size (`SPE.Group`'s `maxParticles` option) than you use then it will only perform draw calls on the sections of the buffers you've used, rather than the whole.

What you're talking about (and you probably know this already!) is fustrum culling. I think it should be fine, but if not let me know. You might have to manually set the `fustrumCulled` property on the mesh IIRC.

**Comment by titansoftime** [comment] 2015-10-24 02:05
Ah ok I see.

**Comment by vincent-courtalon** [comment] 2015-10-27 01:16
just a little followup. I finally managed to get time to update, and it was relatively straightforward (great job!). I must say i like the new way to configure emitters/group.
I will play with the parameters to try to get the same "visual" result as before, but it is already pretty close with a little tweaking. The "wiggle" parameters seem interesting to play with.

as a little bonus, since i just upgraded, i confirm it works fine with the R73 of three, at least with my tests.
thanks for you're work on this library!

**Comment by titansoftime** [comment] 2015-10-27 01:24
>i confirm it works fine with the R73 of three

That's good news =]

**Comment by squarefeet** [comment] 2015-10-27 01:27
Tell me about it. I don't want to have to go through that re-write all over again!

Glad that it's working well for you, @vincent-courtalon. I tried to keep the force integration and various other calculations as close to the previous version as I could, so glad you only have to do a few tweaks. 

Is r73 released already, then, or still in dev? Did I really take that long doing the re-write?!

By the way, there are a few new bugs opened re. the new `rotation` option. I'll get around to fixing them as soon as I can.

**Comment by vincent-courtalon** [comment] 2015-10-27 01:33
r73 is released, it is on the master branch.

Honestly i was surprised, i was planning to use r72, but when i checked on github, saw that r73 was just released a few days ago, so i thought that i might as well update directly to this version and see if it works.

**Comment by squarefeet** [comment] 2015-10-27 01:34
Wow, they don't hang around, do they? I'd best check the changelog...

**Comment by titansoftime** [comment] 2015-10-27 01:34
> Honestly i was surprised

Same here.

**Comment by squarefeet** [comment] 2015-10-27 01:37
The only thing that stands out to me is this, on WebGLRenderer:

* Unified drawRange and group ranges.

I'll have to make sure it's still working as it was in r72 (I'm assuming so...)
